name: 
  en: i18n static template
  fr: modèle statique i18n
  ar: i18n قالب ثابت 
description: 
  en: Multilanguage Jekyll Websites
  fr: Sites Web multilingues Jekyll
  ar: متعدد اللغات مواقع Jekyll
footer:
  en: A project by [smallaxetech]
  de: Ein Projekt von [smallaxetech]
  fr: Un progetto di [smallaxetech]
  ar: مشروع مفتوح المصدر من قبل [smallaxetech]
exclude: ""
permalink: pretty
repository: thesmallaxe/i18-static-template
baseurl: "/i18-static-template"
#baseurl: ""

# Exclude files
exclude: [
  Gemfile.lock,
  Gemfile,
  gulpfile.babel.js,
  node_modules,
  package.json,
  README.md
]

# Build settings
markdown: kramdown
