name: 
  en: i18n static template
  de: i18n statische sjabloon
  it: i18n modello statico
  ar: i18n قالب ثابت 
description: 
  en: Plugin-free multilanguage Jekyll websites
  de: Plugin-freie vielsprachige Jekyll Webseiten
  it: Siti multilingue in Jekyll, senza plugin.
  ar: مجانية مواقع مجانية متعددة اللغات Jekyll متعدد اللغات
footer:
  en: An open-source project by [smallaxetech]
  de: Ein open-source Projekt von [smallaxetech]
  it: Un progetto open-source di [smallaxetech]
  ar: مشروع مفتوح المصدر من قبل [smallaxetech]
exclude: ""
permalink: pretty
repository: thesmallaxe/i18-static-template
baseurl: ""
# baseurl: /polyglot-jekyll
